### ISSUE TITLE
[Feat] Sign in with Apple 세팅 및 구현

### ISSUE THREAD

**Issue by HanGyeongjun** [HanGyeongjun/OrangeBird-iOS#10]
## Summary
- 앱에서 소셜 로그인 기능을 사용하는 상황을 대비해 Sign in with Apple 기능을 구현합니다.

## Goals
- Sign in with 기능 동작

## Plan
- App Store Connect 의 Sign in with 설정 활성화
- Firebase 및 Xcode 설정
- 로그인 코드 작성
- 로그인 뷰 디자인 및 코드 작성

## TODO
- [x] Sign in with Apple 세팅
- [x] Xcode 설정
- [x] 로그인 로직 코드 작성
- [ ] 로그인 뷰 코드 작성

## Additional Context
- 작업 시작 전 필요성에 대해 확실히 정하고 가면 좋을 것 같습니다!
