### ISSUE TITLE
[Feat] 모델 데이터

### ISSUE THREAD

**Issue by flareseek** [HanGyeongjun/OrangeBird-iOS#14]
## Summary
- 필요한 데이터 모델을 작성합니다.

## Goals
- 데이터들의 형식을 구현하여 뷰에서 사용합니다.

## Plan
- 용지로 작성한 모델 데이터 형식을 참조하여 struct로 모델을 구현합니다.

## TODO
- [x] User struct 작성

- [x] Activity struct 작성

- [x] ActivityType enum 작성
- [x] description 반환 함수 작성
- [x] icon 반환 함수 작성
- [x] koreanTitle 반환 함수 작성 

- [x] designationFirst enum 작성

- [x] designationSecond enum 작성

## Additional Context
- 추가로 작성해야할 말이 있으면 작성해주세요.
