### ISSUE TITLE
[Feat] Custom Font 및 Color Set 등록

### ISSUE THREAD

**Issue by HanGyeongjun** [HanGyeongjun/OrangeBird-iOS#3]
## Summary
- App 에서 사용할 Custom Font / Color set을 Extension으로 등록합니다.

## Goals
- 코드 작성 시 Custom 디자인을 쉽게 적용하고 유지보수 할 수 있습니다.

## Plan
- Font Set 결정 및 등록
- Color Set 결정 및 등록
- Extension 작성

## TODO
- [x] Font Set 설정을 위한 Extension 적성
- [x] Color Set 등록
- [x] Sementic Color 사용을 위한 Extension 등록

## Additional Context
- Sementic Color 사용을 위한 사전 합의가 필요합니다.
