### ISSUE TITLE
[Feat] Firebase 설정

### ISSUE THREAD

**Issue by HanGyeongjun** [HanGyeongjun/OrangeBird-iOS#5]
## Summary
- Firebase와 App을 미리 연결해놓습니다.

## Goals
- Firebase를 빠르게 적용할 수 있도록 파일 구조를 제외한 기본적인 연결을 마칩니다.

## Plan
- Firebase 프로젝트 생성 및 기본 세팅
- SPM으로 Firebase 패키지 추가
- 초기화 코드 및 Info-plist 추가

## TODO
- [x] Firebase 프로젝트 생성
- [x] Firebase iOS 세팅
- [x] SPM으로 Firebase 패키지 추가
- [x] 초기화 코드 및 Info-plist 추가
