### ISSUE TITLE
[Feat] Extension 및 범용 코드 작성

### ISSUE THREAD

**Issue by HanGyeongjun** [HanGyeongjun/OrangeBird-iOS#7]
## Summary
- 범용적으로 사용할 수 있는 Extension 및 기타 코드를 작성합니다.

## Goals
- 사전 세팅을 통해 당일 작성이 필요한 코드의 양을 줄입니다. 

## Plan
- Extension 작성
    - UIScreen+Size Extension  : 화면 크기를 구하는 익스텐션
    - Date+String Extension : Date를 가공해 정해진 형태의 String으로 변환하는 익스텐션
    - String+Formatter Extension : SwiftUI의 줄바꿈 문제를 해결하는 변수를 포함하는 익스텐션
- Support 코드 작성
    - HapticManager : 햅틱을 주기 위한 코드
- Component 제작
    - StickyHeader : StickyHeader 구현을 위한 컴포넌트

## TODO
- [x] UIScreen+Size Extension
- [x] Date+String Extension
- [x] String+Formatter Extension
- [x] HapticManager
- [x] StickyHeader

## Additional Context
- 추가로 작성해야 할 사전 코드가 있다면 제안해주세요!
